### PR TITLE
Method for updating rights and supporting retired rights.

### LINKED ISSUE #747: Allow marking which rights are currently active.
### Descriptive summary
Wanted to update the Rights available to the user from offering a selection of Creative Commons 3.0 to 4.0 licenses.  Simply adding licenses makes both the new and old available.  Removing the old licenses breaks the application due to unresolvable terms for the old ids (licenses). 

This came up using CurationConcerns 0.11.  The issue persists to HEAD.

The initial solution landed upon was to add an `active` key to each term.  See related work. 

### Expected behavior
Should be able to update licenses offered, mark the previous ones as no longer active, and support the previous licenses.

`RightsService.select_options` should only display the current options.

### Actual behavior
Adding licenses results in all being offered, and removing previous licenses breaks the QA `label` lookup.  There is no way to mark terms as active or inactive.

`RightsService.select_options` displays all options in rights.yml.

### Steps to reproduce the behavior

1. Create object with rights.
2. Remove or modify the rights id in `config/authorties/rights.yml`
3. View object

### Related work
Have already solved this issue with a monkey patch. mlibrary/umrdr#326

### PR DESCRIPTION
**Pull request by grosscol**
Fixes #747

Allow adding new rights and marking retired rights as inactive.  Still resolve labels for both.

This supports resolving the labels for rights while not offering them as current choices to the users.

Changes proposed in this pull request:
* Add active attribute
* Make rights service utilize active attribute of terms.
* Add fixture file of dummy rights for testing.
* Update rights tests to use fixture file.

@projecthydra/sufia-code-reviewers

### CODE REVIEW

**Comment by jcoyne** [comment]
Looks like rubocop was unhappy.

File: spec/services/rights_service_spec.rb [hunk 1]
```diff
@@ -1,17 +1,29 @@
 require 'spec_helper'
 
 describe RightsService do
-  describe "select_options" do
-    subject { described_class.select_options }
+  before do
+    # Configure QA to use fixtures
+    qa_fixtures = { local_path: File.expand_path('../../fixtures/authorities', __FILE__) }
+    stub_const("Qa::Authorities::LocalSubauthority::AUTHORITIES_CONFIG", qa_fixtures)
```
Comment (grosscol) [inline spec/services/rights_service_spec.rb]: Had to override this constant in order to get QA to read from a different authority file.  Is this an okay way to go about doing this?

Comment (jcoyne) [inline spec/services/rights_service_spec.rb]: We'll it's not optimal that QA doesn't have a better way to do this, but not your problem. 👍
