### PR TITLE
WorkShowPresenter should delegate to solr_doc for date fields fixes fixes #487

### LINKED ISSUE #487: CurationConcerns::WorkShowPresenter should delegate date_[created|modified] to solr_doc
CurationConcerns::WorkShowPresenter should delegate date_created to solr_doc
CurationConcerns::WorkShowPresenter should delegate date_modified to solr_doc

### PR DESCRIPTION
**Pull request by barmintor**

### CODE REVIEW

**Comment by jcoyne** [comment]
Would you please give the commit a more descriptive message so that you don't need to be on github to see what this is all about?

File: curation_concerns-models/app/models/concerns/curation_concerns/solr_document_behavior.rb [hunk 1]
```diff
@@ -44,8 +44,8 @@ def representative_id
       fetch(Solrizer.solr_name('hasRelatedMediaFragment', :symbol), []).first
     end
 
-    def date_uploaded
-      field = self[Solrizer.solr_name('date_uploaded', :stored_sortable, type: :date)]
+    def get_date_field(field_name)
```
Comment (jcoyne) [inline curation_concerns-models/app/models/concerns/curation_concerns/solr_document_behavior.rb]: can you drop the `get_`?

**Comment by mjgiarlo** [comment]
:+1:
